# Generated by Django 4.1.7 on 2023-04-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
