# Generated by Django 4.1.7 on 2023-04-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_wishlist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='list_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='List Name'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
