# Generated by Django 4.2 on 2023-04-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0004_alter_wishlist_list_name_alter_wishlist_slug'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wishlistitem',
            constraint=models.UniqueConstraint(fields=('product', 'wishlist'), name='unique_product_in_wishlist', violation_error_message="Wishlist can't have the same products"),
        ),
    ]
