# Generated by Django 4.2 on 2023-04-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0007_alter_wishlist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='slug',
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='list_name',
            field=models.CharField(max_length=100, verbose_name='List Name'),
        ),
    ]
