# Generated by Django 4.2 on 2023-06-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(default='brands/pixel.png', upload_to='brands'),
            preserve_default=False,
        ),
    ]
