# Generated by Django 4.1.7 on 2023-04-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productdiscount_discount_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='attribute_value',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AttributeValue',
        ),
    ]
