# Generated by Django 4.2 on 2023-04-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productdiscount_discount_unit_greater_than_or_equal_to_minimum_order_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
